<script setup>
import { onMounted, ref } from 'vue'
import AppLayout from '@/layouts/AppLayout.vue'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'
import ErrorAlert from '@/components/common/ErrorAlert.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import companyService from '@/services/company.service'
import { formatEnum } from '@/utils/formatters'
const interviews = ref([]); const loading = ref(true); const error = ref(''); const success = ref(''); const processingId = ref(''); const editing = ref(null); const remarks = ref('')
const feedback = (err, fallback) => err.response?.data?.message || fallback
const load = async () => { loading.value = true; try { interviews.value = await companyService.getCompanyInterviews() } catch (err) { error.value = feedback(err, 'Unable to load interviews.') } finally { loading.value = false } }
const complete = async (item, status) => { processingId.value = item.id; error.value = ''; try { await companyService.completeInterview(item.id, { status, remarks: remarks.value || null }); success.value = `Interview marked ${status.toLowerCase()}.`; remarks.value = ''; await load() } catch (err) { error.value = feedback(err, 'Unable to update interview.') } finally { processingId.value = '' } }
const edit = (item) => { editing.value = { ...item, scheduled_for: new Date(item.scheduled_for).toISOString().slice(0, 16) }; error.value = '' }
const save = async () => { processingId.value = editing.value.id; try { const item = editing.value; await companyService.updateInterview(item.id, { interviewer_name: item.interviewer_name || null, interview_mode: item.interview_mode, meeting_link: item.interview_mode === 'ONLINE' ? item.meeting_link : null, location: item.interview_mode === 'OFFLINE' ? item.location : null, scheduled_for: new Date(item.scheduled_for).toISOString() }); success.value = 'Interview schedule updated.'; editing.value = null; await load() } catch (err) { error.value = feedback(err, 'Unable to update the interview.') } finally { processingId.value = '' } }
onMounted(load)
</script>
<template><AppLayout><div class="container py-4"><h2>Interview Management</h2><ErrorAlert v-if="error" :message="error" /><div v-if="success" class="alert alert-success">{{ success }}</div><form v-if="editing" class="card card-body my-3" @submit.prevent="save"><h5>Reschedule interview</h5><div class="row g-2"><div class="col-md-3"><input v-model="editing.interviewer_name" class="form-control" placeholder="Interviewer"></div><div class="col-md-2"><select v-model="editing.interview_mode" class="form-select"><option>ONLINE</option><option>OFFLINE</option></select></div><div class="col-md-3"><input v-model="editing.scheduled_for" required type="datetime-local" class="form-control"></div><div class="col-md-4"><input v-if="editing.interview_mode === 'ONLINE'" v-model="editing.meeting_link" required type="url" class="form-control" placeholder="Meeting link"><input v-else v-model="editing.location" required class="form-control" placeholder="Location"></div></div><button class="btn btn-primary mt-3 align-self-start" :disabled="processingId === editing.id">Save changes</button></form><LoadingSpinner v-if="loading" /><EmptyState v-else-if="!interviews.length" title="No Interviews" message="Schedule an interview from the applications page." /><div v-else class="table-responsive"><table class="table align-middle"><thead><tr><th>Candidate</th><th>Drive</th><th>Round</th><th>When</th><th>Mode</th><th>Status</th><th>Manage</th></tr></thead><tbody><tr v-for="item in interviews" :key="item.id"><td>{{ item.student_name }}</td><td>{{ item.job_title }}</td><td>{{ item.round_number }}</td><td>{{ new Date(item.scheduled_for).toLocaleString() }}</td><td>{{ formatEnum(item.interview_mode) }}</td><td>{{ formatEnum(item.status) }}</td><td><template v-if="item.status === 'SCHEDULED'"><button class="btn btn-sm btn-outline-primary me-1" @click="edit(item)">Edit</button><button class="btn btn-sm btn-success me-1" :disabled="processingId === item.id" @click="complete(item, 'COMPLETED')">Complete</button><button class="btn btn-sm btn-outline-danger" :disabled="processingId === item.id" @click="complete(item, 'CANCELLED')">Cancel</button></template><span v-else>{{ item.feedback || '—' }}</span></td></tr></tbody></table></div><div v-if="interviews.some(item => item.status === 'SCHEDULED')" class="mt-3"><label class="form-label">Completion remarks (used for the next completion/cancellation)</label><input v-model="remarks" class="form-control" maxlength="2000"></div></div></AppLayout></template>
