<script setup>
import { onMounted, ref } from 'vue'
import AppLayout from '@/layouts/AppLayout.vue'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'
import ErrorAlert from '@/components/common/ErrorAlert.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import driveService from '@/services/company-placement-drive.service'
import companyService from '@/services/company.service'
import { formatEnum } from '@/utils/formatters'

const drives = ref([]); const selectedDrive = ref(''); const applications = ref([])
const loading = ref(true); const error = ref(''); const success = ref(''); const updatingId = ref('')
const scheduling = ref(null)
const interview = ref({ round_number: 1, interviewer_name: '', interview_mode: 'ONLINE', meeting_link: '', location: '', scheduled_for: '' })
const message = (err, fallback) => err.response?.data?.message || fallback
const loadApplications = async () => { if (!selectedDrive.value) return; loading.value = true; error.value = ''; try { applications.value = (await companyService.getDriveApplications(selectedDrive.value, { page: 1, size: 100 })).items } catch (err) { error.value = message(err, 'Unable to load applications.') } finally { loading.value = false } }
const loadDrives = async () => { try { drives.value = (await driveService.getCompanyPlacementDrives({ page: 1, size: 100 })).items; if (drives.value.length) { selectedDrive.value = drives.value[0].id; await loadApplications() } } catch (err) { error.value = message(err, 'Unable to load company drives.') } finally { loading.value = false } }
const update = async (application, action) => { updatingId.value = application.id; error.value = ''; try { await companyService.updateApplicationStatus(application.id, action); success.value = `Application marked ${action.replace('-', ' ')}.`; await loadApplications() } catch (err) { error.value = message(err, 'Unable to update application status.') } finally { updatingId.value = '' } }
const viewResume = async (application) => { updatingId.value = application.id; error.value = ''; try { await companyService.viewApplicationResume(application.id) } catch (err) { error.value = message(err, 'This student has not uploaded a resume.') } finally { updatingId.value = '' } }
const startScheduling = (application) => { scheduling.value = application; interview.value = { round_number: 1, interviewer_name: '', interview_mode: 'ONLINE', meeting_link: '', location: '', scheduled_for: '' }; error.value = ''; success.value = '' }
const createInterview = async () => { updatingId.value = scheduling.value.id; error.value = ''; try { const payload = { ...interview.value, scheduled_for: new Date(interview.value.scheduled_for).toISOString(), meeting_link: interview.value.interview_mode === 'ONLINE' ? interview.value.meeting_link : null, location: interview.value.interview_mode === 'OFFLINE' ? interview.value.location : null }; await companyService.createInterview(scheduling.value.id, payload); success.value = 'Interview scheduled and the student has been moved to interview scheduled.'; scheduling.value = null; await loadApplications() } catch (err) { error.value = message(err, 'Unable to schedule the interview.') } finally { updatingId.value = '' } }
const nextAction = (application) => ({ APPLIED: ['under-review', 'Review'], UNDER_REVIEW: ['shortlist', 'Shortlist'], SHORTLISTED: ['schedule', 'Schedule interview'], INTERVIEW_SCHEDULED: ['select', 'Select'] }[application.application_status])
onMounted(loadDrives)
</script>

<template>
  <AppLayout><div class="container py-4"><h2>Drive Applications</h2>
    <select v-model="selectedDrive" class="form-select my-4" @change="loadApplications"><option v-for="drive in drives" :key="drive.id" :value="drive.id">{{ drive.title }}</option></select>
    <ErrorAlert v-if="error" :message="error" /><div v-if="success" class="alert alert-success">{{ success }}</div>
    <form v-if="scheduling" class="card card-body mb-4" @submit.prevent="createInterview"><div class="d-flex justify-content-between"><h5>Schedule interview: {{ scheduling.student_name }}</h5><button type="button" class="btn-close" @click="scheduling = null" /></div><div class="row g-3"><div class="col-md-2"><label class="form-label">Round</label><input v-model.number="interview.round_number" min="1" required type="number" class="form-control"></div><div class="col-md-4"><label class="form-label">Interviewer</label><input v-model="interview.interviewer_name" class="form-control"></div><div class="col-md-3"><label class="form-label">Mode</label><select v-model="interview.interview_mode" class="form-select"><option value="ONLINE">Online</option><option value="OFFLINE">Offline</option></select></div><div class="col-md-3"><label class="form-label">When</label><input v-model="interview.scheduled_for" required type="datetime-local" class="form-control"></div><div v-if="interview.interview_mode === 'ONLINE'" class="col-md-6"><label class="form-label">Meeting link</label><input v-model.trim="interview.meeting_link" required type="url" class="form-control"></div><div v-else class="col-md-6"><label class="form-label">Location</label><input v-model.trim="interview.location" required class="form-control"></div></div><button class="btn btn-primary mt-3 align-self-start" :disabled="updatingId === scheduling.id">Schedule interview</button></form>
    <LoadingSpinner v-if="loading" /><EmptyState v-else-if="!drives.length" title="No Drives" message="Create a placement drive to receive applications." /><EmptyState v-else-if="!applications.length" title="No Applications" message="No students have applied to this drive yet." />
    <div v-else class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Roll no.</th><th>Branch</th><th>CGPA</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="application in applications" :key="application.id"><td>{{ application.student_name }}</td><td>{{ application.roll_number }}</td><td>{{ application.branch }}</td><td>{{ application.cgpa }}</td><td>{{ formatEnum(application.application_status) }}</td><td class="text-nowrap"><button class="btn btn-sm btn-outline-secondary me-1" :disabled="updatingId === application.id" @click="viewResume(application)">Resume</button><button v-if="nextAction(application)" class="btn btn-sm btn-outline-primary me-1" :disabled="updatingId === application.id" @click="nextAction(application)[0] === 'schedule' ? startScheduling(application) : update(application, nextAction(application)[0])">{{ nextAction(application)[1] }}</button><button v-if="!['SELECTED', 'REJECTED'].includes(application.application_status)" class="btn btn-sm btn-outline-danger" :disabled="updatingId === application.id" @click="update(application, 'reject')">Reject</button></td></tr></tbody></table></div>
  </div></AppLayout>
</template>
