from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_APPLICATION_STATUS_TRANSITION = "INVALID_APPLICATION_STATUS_TRANSITION"
    APPLICATION_NOT_WITHDRAWABLE = "APPLICATION_NOT_WITHDRAWABLE"
    RESUME_NOT_UPLOADED = "RESUME_NOT_UPLOADED"
    ALREADY_APPLIED = "ALREADY_APPLIED"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_NOT_APPROVED = "ACCOUNT_NOT_APPROVED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    UNAUTHORIZED = "UNAUTHORIZED"
    ACCOUNT_BLACKLISTED = "ACCOUNT_BLACKLISTED"
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    COMPANY_ALREADY_EXISTS = "COMPANY_ALREADY_EXISTS"
    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
    COMPANY_ALREADY_REJECTED = "COMPANY_ALREADY_REJECTED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"
    INVALID_APPLICATION_DEADLINE = "INVALID_APPLICATION_DEADLINE"
    INVALID_DATE = "INVALID_DATE"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"