from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_NOT_APPROVED = "ACCOUNT_NOT_APPROVED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    UNAUTHORIZED = "UNAUTHORIZED"
    ACCOUNT_BLACKLISTED = "ACCOUNT_BLACKLISTED"
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    COMPANY_ALREADY_EXISTS = "COMPANY_ALREADY_EXISTS"
    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
    COMPANY_ALREADY_REJECTED = "COMPANY_ALREADY_REJECTED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"