from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_NOT_APPROVED = "ACCOUNT_NOT_APPROVED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    UNAUTHORIZED = "UNAUTHORIZED"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"